{
    "request_number": 1,
    "timestamp": "2025-10-12 19:48:35",
    "model": "deepseek/deepseek-chat-v3-0324",
    "prompt_variant": "zero-shot-clusters",
    "total_tokens": 3424,
    "avg_prob": 0.8802349878926259,
    "perplexity": 1.1360602722621875,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 2.5833333333333335,
        "ast_depth": 13,
        "avg_function_size_lines": 16.45,
        "import_redundancy_ratio": 0.08333333333333333
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 66,
        "mypy_error_count": 1
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 2.293,
        "exception_type": "EnvironmentMismatch",
        "exception_message": "Unable to open configuration file newrelic.ini.",
        "runtime_output": "Traceback (most recent call last):\n  File \"/app/main.py\", line 27, in <module>\n    newrelic.agent.initialize('newrelic.ini')\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 4349, in initialize\n    _load_configuration(config_file, environment, ignore_errors, log_file, log_level)\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 955, in _load_configuration\n    raise newrelic.api.exceptions.ConfigurationError(f\"Unable to open configuration file {config_file}.\")\nnewrelic.api.exceptions.ConfigurationError: Unable to open configuration file newrelic.ini."
    },
    "total_credibility": 59.37
}