{
    "request_number": 16,
    "timestamp": "2025-10-12 12:19:00",
    "model": "deepseek/deepseek-chat-v3-0324",
    "prompt_variant": "zero-shot",
    "total_tokens": 1686,
    "avg_prob": 0.8571104975713825,
    "perplexity": 1.1667107133018368,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 1.875,
        "ast_depth": 13,
        "avg_function_size_lines": 10.5,
        "import_redundancy_ratio": 0.0
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 32,
        "mypy_error_count": 4
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 2.089,
        "exception_type": "EnvironmentMismatch",
        "exception_message": "Unable to open configuration file newrelic.ini.",
        "runtime_output": "Traceback (most recent call last):\n  File \"/app/main.py\", line 14, in <module>\n    newrelic.agent.initialize('newrelic.ini')\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 4349, in initialize\n    _load_configuration(config_file, environment, ignore_errors, log_file, log_level)\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 955, in _load_configuration\n    raise newrelic.api.exceptions.ConfigurationError(f\"Unable to open configuration file {config_file}.\")\nnewrelic.api.exceptions.ConfigurationError: Unable to open configuration file newrelic.ini."
    },
    "total_credibility": 48.16
}