{
    "request_number": 3,
    "timestamp": "2025-10-11 21:23:36",
    "model": "deepseek/deepseek-chat-v3-0324",
    "prompt_variant": "zero-shot",
    "total_tokens": 3029,
    "avg_prob": 0.8821753409290208,
    "perplexity": 1.1335614969093306,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 2.6,
        "ast_depth": 17,
        "avg_function_size_lines": 17.11764705882353,
        "import_redundancy_ratio": 0.16666666666666666
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 45,
        "mypy_error_count": 12
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 3.013,
        "exception_type": "EnvironmentMismatch",
        "exception_message": "Unable to open configuration file newrelic.ini.",
        "runtime_output": "/app/main.py:17: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)\n  Base = declarative_base()\nTraceback (most recent call last):\n  File \"/app/main.py\", line 25, in <module>\n    newrelic.agent.initialize('newrelic.ini')\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 4349, in initialize\n    _load_configuration(config_file, environment, ignore_errors, log_file, log_level)\n  File \"/usr/local/lib/python3.11/site-packages/newrelic/config.py\", line 955, in _load_configuration\n    raise newrelic.api.exceptions.ConfigurationError(f\"Unable to open configuration file {config_file}.\")\nnewrelic.api.exceptions.ConfigurationError: Unable to open configuration file newrelic.ini."
    },
    "total_credibility": 50.16
}