{
    "request_number": 12,
    "timestamp": "2025-10-12 12:43:16",
    "model": "x-ai/grok-4-fast",
    "prompt_variant": "zero-shot",
    "total_tokens": 8087,
    "avg_prob": 0.925572106915608,
    "perplexity": 1.080412852254609,
    "struct_metrics": {
        "avg_cyclomatic_complexity": 1.6504854368932038,
        "ast_depth": 14,
        "avg_function_size_lines": 4.309278350515464,
        "import_redundancy_ratio": 0.13333333333333333
    },
    "semantic_metrics": {
        "syntax_valid": true,
        "flake8_error_count": 16,
        "mypy_error_count": 22
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 3.74,
        "exception_type": "NameError",
        "exception_message": "name 'Tuple' is not defined. Did you mean: 'tuple'?",
        "runtime_output": "/app/main.py:20: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)\n  Base = declarative_base()\nTraceback (most recent call last):\n  File \"/app/main.py\", line 62, in <module>\n    class BrokerSystem:\n  File \"/app/main.py\", line 232, in BrokerSystem\n    def generate_error_files(self, submission_file: str, errors: List[str], warnings: List[str]) -> Tuple[str, str]:\n                                                                                                    ^^^^^\nNameError: name 'Tuple' is not defined. Did you mean: 'tuple'?"
    },
    "total_credibility": 32.76
}